import type { Lang } from './translations';

export const qualificationCopy: Record<Lang, { licence: string; authorization: string; required: string; privacy: string; policy: string }> = {
  es: { licence: '¿Tienes permiso de conducir C+E en vigor?', authorization: '¿Tienes derecho a trabajar en Alemania?', required: 'Se requiere una respuesta afirmativa para solicitar este puesto.', privacy: 'He leído la información sobre el tratamiento de mis datos para gestionar mi candidatura.', policy: 'Política de privacidad' },
  en: { licence: 'Do you hold a valid C+E driving licence?', authorization: 'Are you authorized to work in Germany?', required: 'A yes answer is required to apply for this role.', privacy: 'I have read the information about processing my data for this application.', policy: 'Privacy policy' },
  de: { licence: 'Haben Sie einen gültigen Führerschein der Klasse C+E?', authorization: 'Sind Sie berechtigt, in Deutschland zu arbeiten?', required: 'Für diese Stelle ist eine Ja-Antwort erforderlich.', privacy: 'Ich habe die Informationen zur Verarbeitung meiner Bewerbungsdaten gelesen.', policy: 'Datenschutzerklärung' },
  pl: { licence: 'Czy masz ważne prawo jazdy C+E?', authorization: 'Czy masz prawo do pracy w Niemczech?', required: 'Aby aplikować, musisz odpowiedzieć tak.', privacy: 'Zapoznałem(-am) się z informacjami o przetwarzaniu danych mojej aplikacji.', policy: 'Polityka prywatności' },
  uk: { licence: 'У вас є чинне посвідчення водія категорії C+E?', authorization: 'Ви маєте право працювати в Німеччині?', required: 'Для подання заявки необхідна відповідь «Так».', privacy: 'Я ознайомився(-лася) з інформацією про обробку даних заявки.', policy: 'Політика конфіденційності' },
  sq: { licence: 'A keni leje drejtimi C+E të vlefshme?', authorization: 'A keni të drejtë të punoni në Gjermani?', required: 'Për të aplikuar kërkohet përgjigjja Po.', privacy: 'Kam lexuar informacionin për përpunimin e të dhënave të aplikimit tim.', policy: 'Politika e privatësisë' },
  ro: { licence: 'Ai permis de conducere C+E valabil?', authorization: 'Ai dreptul de a lucra în Germania?', required: 'Pentru a aplica trebuie să răspunzi Da.', privacy: 'Am citit informațiile privind prelucrarea datelor candidaturii mele.', policy: 'Politica de confidențialitate' },
  el: { licence: 'Έχετε έγκυρη άδεια οδήγησης C+E;', authorization: 'Έχετε δικαίωμα εργασίας στη Γερμανία;', required: 'Απαιτείται θετική απάντηση για την αίτηση.', privacy: 'Έχω διαβάσει τις πληροφορίες για την επεξεργασία των δεδομένων της αίτησής μου.', policy: 'Πολιτική απορρήτου' },
  ru: { licence: 'У вас есть действующее водительское удостоверение C+E?', authorization: 'У вас есть право работать в Германии?', required: 'Для подачи заявки нужен ответ «Да».', privacy: 'Я ознакомился(-лась) с информацией об обработке данных моей заявки.', policy: 'Политика конфиденциальности' },
  sr: { licence: 'Da li imate važeću vozačku dozvolu C+E?', authorization: 'Da li imate pravo na rad u Nemačkoj?', required: 'Za prijavu je potreban odgovor Da.', privacy: 'Pročitao/la sam informacije o obradi podataka moje prijave.', policy: 'Politika privatnosti' },
  ar: { licence: 'هل لديك رخصة قيادة C+E سارية؟', authorization: 'هل يحق لك العمل في ألمانيا؟', required: 'يلزم اختيار نعم للتقدم لهذه الوظيفة.', privacy: 'قرأت معلومات معالجة بيانات طلبي الوظيفي.', policy: 'سياسة الخصوصية' },
};
