import type { Lang } from './translations';

export const siteCopy: Record<Lang, { requirements: [string, string, string]; cookies: string; reject: string; accept: string; settings: string }> = {
  es: { requirements: ['Carnet C+E en vigor', 'CAP / Código 95 en vigor', 'Derecho a trabajar en Alemania'], cookies: 'Usamos cookies de medición de Google Ads solo si las aceptas. Puedes solicitar el empleo aunque las rechaces.', reject: 'Rechazar', accept: 'Aceptar', settings: 'Configurar cookies' },
  en: { requirements: ['Valid C+E driving licence', 'Valid driver qualification / Code 95', 'Right to work in Germany'], cookies: 'We use Google Ads measurement cookies only if you accept. You can apply without accepting.', reject: 'Reject', accept: 'Accept', settings: 'Cookie settings' },
  de: { requirements: ['Gültiger Führerschein C+E', 'Gültige Fahrerqualifikation / Code 95', 'Berechtigung zur Arbeit in Deutschland'], cookies: 'Wir verwenden Google Ads-Messcookies nur mit Ihrer Zustimmung. Sie können sich auch ohne Zustimmung bewerben.', reject: 'Ablehnen', accept: 'Akzeptieren', settings: 'Cookie-Einstellungen' },
  pl: { requirements: ['Ważne prawo jazdy C+E', 'Ważny kod 95 / kwalifikacja kierowcy', 'Prawo do pracy w Niemczech'], cookies: 'Używamy plików cookie Google Ads tylko za Twoją zgodą. Możesz aplikować także bez zgody.', reject: 'Odrzuć', accept: 'Akceptuj', settings: 'Ustawienia cookies' },
  uk: { requirements: ['Чинне посвідчення водія C+E', 'Чинний код 95 / кваліфікація водія', 'Право на роботу в Німеччині'], cookies: 'Ми використовуємо файли cookie Google Ads лише за вашою згодою. Ви можете подати заявку без згоди.', reject: 'Відхилити', accept: 'Прийняти', settings: 'Налаштування cookie' },
  sq: { requirements: ['Patentë C+E e vlefshme', 'Kodi 95 / kualifikimi i shoferit i vlefshëm', 'E drejta për të punuar në Gjermani'], cookies: 'Përdorim cookie matëse të Google Ads vetëm me pëlqimin tuaj. Mund të aplikoni edhe pa i pranuar.', reject: 'Refuzo', accept: 'Prano', settings: 'Cilësimet e cookie-ve' },
  ro: { requirements: ['Permis C+E valabil', 'Cod 95 / calificare profesională valabilă', 'Drept de muncă în Germania'], cookies: 'Folosim cookie-uri de măsurare Google Ads doar cu acordul tău. Poți aplica și fără să le accepți.', reject: 'Refuză', accept: 'Acceptă', settings: 'Setări cookie-uri' },
  el: { requirements: ['Έγκυρη άδεια οδήγησης C+E', 'Έγκυρος κωδικός 95 / επαγγελματική κατάρτιση', 'Δικαίωμα εργασίας στη Γερμανία'], cookies: 'Χρησιμοποιούμε cookies μέτρησης Google Ads μόνο με τη συγκατάθεσή σας. Μπορείτε να υποβάλετε αίτηση χωρίς αυτά.', reject: 'Απόρριψη', accept: 'Αποδοχή', settings: 'Ρυθμίσεις cookies' },
  ru: { requirements: ['Действующие права C+E', 'Действующий код 95 / квалификация водителя', 'Право на работу в Германии'], cookies: 'Мы используем cookie Google Ads только с вашего согласия. Подать заявку можно и без согласия.', reject: 'Отклонить', accept: 'Принять', settings: 'Настройки cookie' },
  sr: { requirements: ['Važeća vozačka dozvola C+E', 'Važeći kod 95 / kvalifikacija vozača', 'Pravo na rad u Nemačkoj'], cookies: 'Koristimo Google Ads kolačiće samo uz vaš pristanak. Možete se prijaviti i bez prihvatanja.', reject: 'Odbij', accept: 'Prihvati', settings: 'Podešavanja kolačića' },
  ar: { requirements: ['رخصة قيادة C+E سارية', 'الرمز 95 / تأهيل مهني سارٍ', 'الحق في العمل في ألمانيا'], cookies: 'نستخدم ملفات تعريف ارتباط Google Ads للقياس بموافقتك فقط. يمكنك التقدم للوظيفة دون قبولها.', reject: 'رفض', accept: 'قبول', settings: 'إعدادات ملفات الارتباط' },
};
